import type { TasteProfile } from "@/lib/taste";

export type CriticSeed = {
  slug: string;
  name: string;
  avatar: string;
  platform: string;
  outlet: string;
  baseUrl: string;
  bio: string;
  tagline: string;
  preferredComplexity: number;
  tasteProfile: TasteProfile;
};

export const critics: CriticSeed[] = [
  {
    slug: "greta-ledger",
    name: "Greta Ledger",
    avatar: "GL",
    platform: "Blog",
    outlet: "Meeple Metrics",
    baseUrl: "https://meeplemetrics.example",
    bio: "Former economist turned critic obsessed with razor-tight euros, efficiency puzzles, and scoring arcs that reward perfect planning.",
    tagline: "Heavy euro evangelist",
    preferredComplexity: 4.4,
    tasteProfile: { strategy: 96, thematic: 34, party: 12, family: 25, solo: 68, conflict: 43 },
  },
  {
    slug: "theo-sparks",
    name: "Theo Sparks",
    avatar: "TS",
    platform: "Podcast",
    outlet: "Table Talk FM",
    baseUrl: "https://tabletalkfm.example",
    bio: "Theo hunts for games that light up a room fast, especially party hits and teach-in-five-minute crowd pleasers.",
    tagline: "Party game pulse checker",
    preferredComplexity: 1.9,
    tasteProfile: { strategy: 38, thematic: 52, party: 97, family: 88, solo: 21, conflict: 35 },
  },
  {
    slug: "mina-vale",
    name: "Mina Vale",
    avatar: "MV",
    platform: "YouTube",
    outlet: "Cardboard Cut",
    baseUrl: "https://cardboardcut.example",
    bio: "Mina loves dramatic arcs, immersive worlds, and production that makes every session feel like an event.",
    tagline: "Narrative table storyteller",
    preferredComplexity: 3.7,
    tasteProfile: { strategy: 58, thematic: 96, party: 28, family: 35, solo: 74, conflict: 69 },
  },
  {
    slug: "owen-park",
    name: "Owen Park",
    avatar: "OP",
    platform: "Blog",
    outlet: "First Turn Family",
    baseUrl: "https://firstturnfamily.example",
    bio: "Owen reviews games for mixed-age tables, valuing accessibility, replayability, and ease of getting back to the fun.",
    tagline: "Gateway and family curator",
    preferredComplexity: 2.1,
    tasteProfile: { strategy: 49, thematic: 44, party: 63, family: 98, solo: 26, conflict: 19 },
  },
  {
    slug: "priya-nandi",
    name: "Priya Nandi",
    avatar: "PN",
    platform: "Podcast",
    outlet: "Decision Space",
    baseUrl: "https://decisionspace.example",
    bio: "Priya chases elegant systems, crunchy puzzles, and games where every turn opens a new line of play.",
    tagline: "Abstract strategy specialist",
    preferredComplexity: 4.0,
    tasteProfile: { strategy: 91, thematic: 41, party: 18, family: 22, solo: 57, conflict: 47 },
  },
  {
    slug: "luca-marsh",
    name: "Luca Marsh",
    avatar: "LM",
    platform: "YouTube",
    outlet: "Weekend Wargamer",
    baseUrl: "https://weekendwargamer.example",
    bio: "Luca spotlights tactical clashes, daring reversals, and games where table tension matters as much as optimization.",
    tagline: "Conflict-driven tactician",
    preferredComplexity: 3.5,
    tasteProfile: { strategy: 67, thematic: 78, party: 24, family: 16, solo: 39, conflict: 98 },
  },
  {
    slug: "samira-holt",
    name: "Samira Holt",
    avatar: "SH",
    platform: "Newsletter",
    outlet: "Solo Mode",
    baseUrl: "https://solomode.example",
    bio: "Samira focuses on co-op arcs, smart solo bots, and designs that scale beautifully from one player to full groups.",
    tagline: "Solo and co-op whisperer",
    preferredComplexity: 3.3,
    tasteProfile: { strategy: 74, thematic: 71, party: 22, family: 34, solo: 99, conflict: 25 },
  },
  {
    slug: "benji-cruz",
    name: "Benji Cruz",
    avatar: "BC",
    platform: "Shorts",
    outlet: "Snack Table",
    baseUrl: "https://snacktable.example",
    bio: "Benji loves bold hooks, quick turns, and games that create instant stories before the snacks run out.",
    tagline: "Fast-fun enthusiast",
    preferredComplexity: 2.2,
    tasteProfile: { strategy: 44, thematic: 61, party: 84, family: 66, solo: 18, conflict: 55 },
  },
  {
    slug: "clara-bishop",
    name: "Clara Bishop",
    avatar: "CB",
    platform: "Blog",
    outlet: "Duel Ledger",
    baseUrl: "https://duelledger.example",
    bio: "Clara is happiest with tight two-player systems, tense tempo races, and interaction that feels surgical instead of chaotic.",
    tagline: "Two-player duel analyst",
    preferredComplexity: 2.7,
    tasteProfile: { strategy: 84, thematic: 38, party: 14, family: 31, solo: 11, conflict: 58 },
  },
  {
    slug: "hector-ruiz",
    name: "Hector Ruiz",
    avatar: "HR",
    platform: "Longform",
    outlet: "Campaign Cartographer",
    baseUrl: "https://campaigncartographer.example",
    bio: "Hector covers sprawling campaigns, historical sandboxes, and simulation-heavy games that reward a full weekend commitment.",
    tagline: "Campaign and simulation devotee",
    preferredComplexity: 4.5,
    tasteProfile: { strategy: 88, thematic: 84, party: 5, family: 8, solo: 76, conflict: 66 },
  },
  {
    slug: "naomi-hart",
    name: "Naomi Hart",
    avatar: "NH",
    platform: "Newsletter",
    outlet: "Cozy Cardboard",
    baseUrl: "https://cozycardboard.example",
    bio: "Naomi champions tactile production, welcoming rules, and cozy themes that still leave room for meaningful choices.",
    tagline: "Cozy family tastemaker",
    preferredComplexity: 2.4,
    tasteProfile: { strategy: 56, thematic: 67, party: 41, family: 94, solo: 44, conflict: 12 },
  },
  {
    slug: "jasper-flynn",
    name: "Jasper Flynn",
    avatar: "JF",
    platform: "Video Essay",
    outlet: "Shuffled Frames",
    baseUrl: "https://shuffledframes.example",
    bio: "Jasper chases clever fillers, dexterity showpieces, and social games with one killer idea executed cleanly.",
    tagline: "Filler and dexterity scout",
    preferredComplexity: 1.7,
    tasteProfile: { strategy: 41, thematic: 46, party: 91, family: 72, solo: 9, conflict: 38 },
  },
  {
    slug: "viv-chen",
    name: "Viv Chen",
    avatar: "VC",
    platform: "Blog",
    outlet: "Engine Room",
    baseUrl: "https://engineroom.example",
    bio: "Viv focuses on combo engines, clever action economies, and the little rules interactions that separate good strategy games from great ones.",
    tagline: "Engine-builder obsessive",
    preferredComplexity: 3.8,
    tasteProfile: { strategy: 94, thematic: 52, party: 10, family: 24, solo: 63, conflict: 29 },
  },
  {
    slug: "elena-petrov",
    name: "Elena Petrov",
    avatar: "EP",
    platform: "Podcast",
    outlet: "After Hours Table",
    baseUrl: "https://afterhourstable.example",
    bio: "Elena seeks atmospheric games that generate dread, surprise, and stories players keep retelling on the drive home.",
    tagline: "Horror and spectacle critic",
    preferredComplexity: 3.4,
    tasteProfile: { strategy: 53, thematic: 97, party: 21, family: 14, solo: 58, conflict: 79 },
  },
];
