import type { TasteProfile } from "@/lib/taste";

export type GameSeed = {
  title: string;
  year: number;
  categories: string[];
  mechanics: string[];
  minPlayers: number;
  maxPlayers: number;
  complexity: number;
  playTime: number;
  hook: string;
  buzz: number;
  rising: number;
  tasteProfile: TasteProfile;
};

export const gameSeeds: GameSeed[] = [
  { title: "Wingspan", year: 2019, categories: ["Engine Building", "Nature"], mechanics: ["Card Drafting", "Engine Building", "Set Collection"], minPlayers: 1, maxPlayers: 5, complexity: 2.6, playTime: 70, hook: "build a thriving bird preserve with satisfying combos and table presence", buzz: 86, rising: 58, tasteProfile: { strategy: 74, thematic: 58, party: 20, family: 61, solo: 71, conflict: 11 } },
  { title: "Brass: Birmingham", year: 2018, categories: ["Economic", "Strategy"], mechanics: ["Network Building", "Hand Management", "Route Building"], minPlayers: 2, maxPlayers: 4, complexity: 4.5, playTime: 130, hook: "race industrial rivals across canals and rails in a brutally efficient economy", buzz: 92, rising: 64, tasteProfile: { strategy: 98, thematic: 46, party: 5, family: 10, solo: 32, conflict: 56 } },
  { title: "Ark Nova", year: 2021, categories: ["Strategy", "Zoo"], mechanics: ["Card Synergy", "Action Selection", "Tableau Building"], minPlayers: 1, maxPlayers: 4, complexity: 4.3, playTime: 150, hook: "design a modern zoo powered by sprawling card synergies and razor-thin efficiency", buzz: 95, rising: 72, tasteProfile: { strategy: 97, thematic: 55, party: 6, family: 14, solo: 69, conflict: 20 } },
  { title: "Heat: Pedal to the Metal", year: 2022, categories: ["Racing", "Family"], mechanics: ["Hand Management", "Push Your Luck", "Simultaneous Play"], minPlayers: 1, maxPlayers: 6, complexity: 2.2, playTime: 55, hook: "thread corners at impossible speed in a racing game that feels instantly cinematic", buzz: 89, rising: 76, tasteProfile: { strategy: 56, thematic: 74, party: 63, family: 79, solo: 41, conflict: 52 } },
  { title: "Spirit Island", year: 2017, categories: ["Co-op", "Defense"], mechanics: ["Variable Powers", "Area Control", "Hand Management"], minPlayers: 1, maxPlayers: 4, complexity: 4.4, playTime: 130, hook: "push colonial invaders off your island with deeply asymmetric spirit powers", buzz: 91, rising: 61, tasteProfile: { strategy: 88, thematic: 82, party: 8, family: 18, solo: 98, conflict: 41 } },
  { title: "Cascadia", year: 2021, categories: ["Tile Laying", "Nature"], mechanics: ["Pattern Building", "Tile Drafting", "Spatial Puzzle"], minPlayers: 1, maxPlayers: 4, complexity: 2.0, playTime: 40, hook: "stitch habitats and wildlife into a wonderfully gentle spatial puzzle", buzz: 83, rising: 57, tasteProfile: { strategy: 61, thematic: 52, party: 22, family: 91, solo: 56, conflict: 9 } },
  { title: "Azul", year: 2017, categories: ["Abstract", "Family"], mechanics: ["Pattern Building", "Drafting", "Set Collection"], minPlayers: 2, maxPlayers: 4, complexity: 1.9, playTime: 35, hook: "draft dazzling tiles into a razor-clean abstract puzzle", buzz: 84, rising: 49, tasteProfile: { strategy: 72, thematic: 24, party: 34, family: 83, solo: 18, conflict: 16 } },
  { title: "Root", year: 2018, categories: ["Conflict", "Asymmetric"], mechanics: ["Area Control", "Card Crafting", "Faction Play"], minPlayers: 2, maxPlayers: 4, complexity: 3.8, playTime: 95, hook: "wage a woodland war where every faction rewrites the rules", buzz: 90, rising: 68, tasteProfile: { strategy: 79, thematic: 84, party: 12, family: 18, solo: 26, conflict: 96 } },
  { title: "Gloomhaven", year: 2017, categories: ["Campaign", "Adventure"], mechanics: ["Hand Management", "Dungeon Crawl", "Legacy"], minPlayers: 1, maxPlayers: 4, complexity: 3.9, playTime: 120, hook: "hack through a massive campaign using clever card timing instead of dice swings", buzz: 88, rising: 44, tasteProfile: { strategy: 77, thematic: 97, party: 6, family: 9, solo: 93, conflict: 54 } },
  { title: "The Crew", year: 2019, categories: ["Co-op", "Card Game"], mechanics: ["Trick Taking", "Mission-based Play", "Communication Limits"], minPlayers: 2, maxPlayers: 5, complexity: 2.2, playTime: 25, hook: "turn a humble trick-taking deck into a mission-driven cooperative masterpiece", buzz: 80, rising: 53, tasteProfile: { strategy: 67, thematic: 39, party: 46, family: 73, solo: 18, conflict: 14 } },
  { title: "Terraforming Mars", year: 2016, categories: ["Engine Building", "Sci-Fi"], mechanics: ["Tableau Building", "Resource Management", "Card Play"], minPlayers: 1, maxPlayers: 5, complexity: 3.6, playTime: 140, hook: "build interlocking engines while turning Mars into a livable frontier", buzz: 87, rising: 48, tasteProfile: { strategy: 91, thematic: 72, party: 7, family: 18, solo: 85, conflict: 19 } },
  { title: "Dune: Imperium", year: 2020, categories: ["Deckbuilding", "Conflict"], mechanics: ["Worker Placement", "Deck Building", "Area Majority"], minPlayers: 1, maxPlayers: 4, complexity: 3.5, playTime: 110, hook: "blend deckbuilding and worker placement inside a tense desert power struggle", buzz: 93, rising: 71, tasteProfile: { strategy: 89, thematic: 87, party: 11, family: 14, solo: 58, conflict: 82 } },
  { title: "Scout", year: 2019, categories: ["Card Game", "Party"], mechanics: ["Hand Management", "Ladder Climbing", "Tempo Play"], minPlayers: 2, maxPlayers: 5, complexity: 1.8, playTime: 20, hook: "use one unchangeable hand to create surprising tempo swings and table cheers", buzz: 78, rising: 63, tasteProfile: { strategy: 58, thematic: 22, party: 82, family: 67, solo: 9, conflict: 24 } },
  { title: "Skull", year: 2011, categories: ["Bluffing", "Party"], mechanics: ["Bluffing", "Betting", "Deduction"], minPlayers: 3, maxPlayers: 6, complexity: 1.2, playTime: 20, hook: "turn four coasters into a bluffing knife fight", buzz: 72, rising: 36, tasteProfile: { strategy: 32, thematic: 44, party: 95, family: 58, solo: 5, conflict: 51 } },
  { title: "Everdell", year: 2018, categories: ["Engine Building", "Fantasy"], mechanics: ["Worker Placement", "Tableau Building", "Card Synergy"], minPlayers: 1, maxPlayers: 4, complexity: 2.9, playTime: 85, hook: "grow a charming forest city packed with cozy combos and tactile delight", buzz: 85, rising: 52, tasteProfile: { strategy: 70, thematic: 78, party: 18, family: 54, solo: 63, conflict: 13 } },
  { title: "Lost Ruins of Arnak", year: 2020, categories: ["Adventure", "Deckbuilding"], mechanics: ["Deck Building", "Worker Placement", "Resource Conversion"], minPlayers: 1, maxPlayers: 4, complexity: 3.1, playTime: 95, hook: "explore a pulpy island while your deck and action economy steadily sharpen", buzz: 84, rising: 59, tasteProfile: { strategy: 79, thematic: 83, party: 12, family: 28, solo: 73, conflict: 21 } },
  { title: "Puerto Rico 1897", year: 2023, categories: ["Economic", "Euro"], mechanics: ["Role Selection", "Engine Building", "Production"], minPlayers: 2, maxPlayers: 5, complexity: 3.5, playTime: 100, hook: "chain role choices and production timing in a refreshed classic euro", buzz: 75, rising: 55, tasteProfile: { strategy: 89, thematic: 31, party: 6, family: 19, solo: 36, conflict: 24 } },
  { title: "Harmonies", year: 2024, categories: ["Nature", "Puzzle"], mechanics: ["Pattern Building", "Token Placement", "Set Collection"], minPlayers: 1, maxPlayers: 4, complexity: 2.1, playTime: 35, hook: "layer mountains, forests, and wildlife into a gorgeous little drafting puzzle", buzz: 88, rising: 84, tasteProfile: { strategy: 63, thematic: 58, party: 24, family: 86, solo: 52, conflict: 8 } },
  { title: "Earth", year: 2023, categories: ["Engine Building", "Nature"], mechanics: ["Tableau Building", "Simultaneous Turns", "Combo Chaining"], minPlayers: 1, maxPlayers: 5, complexity: 2.9, playTime: 80, hook: "trigger lush chain reactions as everyone grows ecosystems together", buzz: 81, rising: 62, tasteProfile: { strategy: 77, thematic: 63, party: 18, family: 47, solo: 69, conflict: 11 } },
  { title: "Splendor Duel", year: 2022, categories: ["Abstract", "Two-Player"], mechanics: ["Drafting", "Set Collection", "Tactical Tempo"], minPlayers: 2, maxPlayers: 2, complexity: 2.2, playTime: 35, hook: "compress gem drafting into a tense duel full of sharp tactical pivots", buzz: 79, rising: 58, tasteProfile: { strategy: 75, thematic: 29, party: 17, family: 64, solo: 8, conflict: 31 } },
  { title: "Hegemony", year: 2023, categories: ["Political", "Economic"], mechanics: ["Asymmetric Roles", "Negotiation", "Economic Simulation"], minPlayers: 2, maxPlayers: 4, complexity: 4.2, playTime: 170, hook: "play competing classes in a dense political economy sandbox", buzz: 77, rising: 69, tasteProfile: { strategy: 94, thematic: 69, party: 4, family: 5, solo: 22, conflict: 73 } },
  { title: "Apiary", year: 2023, categories: ["Sci-Fi", "Euro"], mechanics: ["Worker Placement", "Variable Setup", "Engine Building"], minPlayers: 1, maxPlayers: 5, complexity: 3.3, playTime: 95, hook: "command spacefaring bees in a euro that thrives on clever worker timing", buzz: 76, rising: 66, tasteProfile: { strategy: 85, thematic: 61, party: 11, family: 24, solo: 61, conflict: 18 } },
  { title: "The Quacks of Quedlinburg", year: 2018, categories: ["Push Your Luck", "Family"], mechanics: ["Bag Building", "Push Your Luck", "Simultaneous Play"], minPlayers: 2, maxPlayers: 4, complexity: 1.9, playTime: 45, hook: "brew absurd potions while your bag-building greed threatens to explode the whole plan", buzz: 82, rising: 47, tasteProfile: { strategy: 54, thematic: 62, party: 78, family: 89, solo: 15, conflict: 12 } },
  { title: "Nemesis", year: 2018, categories: ["Sci-Fi", "Horror"], mechanics: ["Semi-Coop", "Hidden Objectives", "Exploration"], minPlayers: 1, maxPlayers: 5, complexity: 3.5, playTime: 140, hook: "survive an alien-infested ship where trust breaks just as fast as the hull", buzz: 86, rising: 51, tasteProfile: { strategy: 57, thematic: 98, party: 26, family: 8, solo: 61, conflict: 88 } },
  { title: "Dorfromantik", year: 2022, categories: ["Co-op", "Puzzle"], mechanics: ["Tile Laying", "Campaign", "Scenario Unlocks"], minPlayers: 1, maxPlayers: 6, complexity: 1.8, playTime: 45, hook: "turn a peaceful landscape into a campaign of cozy cooperative goals", buzz: 74, rising: 56, tasteProfile: { strategy: 52, thematic: 47, party: 28, family: 85, solo: 72, conflict: 4 } },
  { title: "Pandemic Legacy: Season 1", year: 2015, categories: ["Legacy", "Co-op"], mechanics: ["Hand Management", "Campaign", "Variable Rules"], minPlayers: 2, maxPlayers: 4, complexity: 2.9, playTime: 65, hook: "save the world over a year-long co-op campaign that keeps escalating", buzz: 79, rising: 28, tasteProfile: { strategy: 68, thematic: 89, party: 12, family: 39, solo: 33, conflict: 15 } },
  { title: "7 Wonders Duel", year: 2015, categories: ["Card Drafting", "Two-Player"], mechanics: ["Pyramid Drafting", "Engine Building", "Set Collection"], minPlayers: 2, maxPlayers: 2, complexity: 2.3, playTime: 30, hook: "outmaneuver a rival across military, science, and civic timing windows", buzz: 80, rising: 35, tasteProfile: { strategy: 78, thematic: 32, party: 18, family: 52, solo: 6, conflict: 43 } },
  { title: "Tapestry", year: 2019, categories: ["Civilization", "Strategy"], mechanics: ["Track Advancement", "Engine Building", "Asymmetric Civ Powers"], minPlayers: 1, maxPlayers: 5, complexity: 2.8, playTime: 110, hook: "chart an alternate-history civilization through punchy turns and giant swings", buzz: 70, rising: 33, tasteProfile: { strategy: 73, thematic: 69, party: 11, family: 24, solo: 47, conflict: 27 } },
  { title: "Clank! Catacombs", year: 2022, categories: ["Adventure", "Deckbuilding"], mechanics: ["Deck Building", "Exploration", "Push Your Luck"], minPlayers: 2, maxPlayers: 4, complexity: 2.6, playTime: 90, hook: "dive into a modular dungeon where every noisy shortcut invites more danger", buzz: 81, rising: 73, tasteProfile: { strategy: 58, thematic: 87, party: 47, family: 31, solo: 22, conflict: 49 } },
  { title: "Wonderland's War", year: 2022, categories: ["Conflict", "Bag Building"], mechanics: ["Area Majority", "Bag Building", "Asymmetric Powers"], minPlayers: 2, maxPlayers: 5, complexity: 3.3, playTime: 125, hook: "fight whimsical battles where bag pulls create wild swings and table stories", buzz: 78, rising: 67, tasteProfile: { strategy: 61, thematic: 92, party: 24, family: 19, solo: 16, conflict: 94 } },
  { title: "Frosthaven", year: 2022, categories: ["Campaign", "Adventure"], mechanics: ["Hand Management", "Scenario Campaign", "Town Building"], minPlayers: 1, maxPlayers: 4, complexity: 4.2, playTime: 150, hook: "expand a frozen outpost through tactical scenarios and a huge branching campaign", buzz: 82, rising: 46, tasteProfile: { strategy: 83, thematic: 97, party: 5, family: 7, solo: 88, conflict: 52 } },
  { title: "Parks", year: 2019, categories: ["Nature", "Family"], mechanics: ["Worker Movement", "Set Collection", "Resource Conversion"], minPlayers: 1, maxPlayers: 5, complexity: 2.2, playTime: 45, hook: "wander national parks in a breezy production showcase full of postcard charm", buzz: 73, rising: 39, tasteProfile: { strategy: 53, thematic: 66, party: 24, family: 82, solo: 56, conflict: 6 } },
  { title: "Crokinole", year: 1876, categories: ["Dexterity", "Classic"], mechanics: ["Flicking", "Precision", "Direct Interaction"], minPlayers: 2, maxPlayers: 4, complexity: 1.1, playTime: 25, hook: "flick discs with absurd precision in the most elegant dexterity duel around", buzz: 68, rising: 25, tasteProfile: { strategy: 28, thematic: 21, party: 61, family: 71, solo: 4, conflict: 58 } },
  { title: "Codenames", year: 2015, categories: ["Party", "Word Game"], mechanics: ["Word Association", "Teams", "Deduction"], minPlayers: 4, maxPlayers: 8, complexity: 1.3, playTime: 20, hook: "link one-word clues to impossible chains of associations and inside jokes", buzz: 81, rising: 29, tasteProfile: { strategy: 36, thematic: 33, party: 99, family: 86, solo: 2, conflict: 13 } },
  { title: "Ready Set Bet", year: 2022, categories: ["Party", "Racing"], mechanics: ["Real-Time Betting", "Racing", "Cheering"], minPlayers: 2, maxPlayers: 9, complexity: 1.7, playTime: 45, hook: "capture horse-track chaos with simultaneous bets and huge screams", buzz: 76, rising: 74, tasteProfile: { strategy: 41, thematic: 61, party: 96, family: 68, solo: 1, conflict: 24 } },
  { title: "Sky Team", year: 2023, categories: ["Co-op", "Two-Player"], mechanics: ["Dice Placement", "Communication Limits", "Scenario Goals"], minPlayers: 2, maxPlayers: 2, complexity: 2.3, playTime: 30, hook: "land a passenger jet together through tense two-player communication puzzles", buzz: 87, rising: 91, tasteProfile: { strategy: 72, thematic: 78, party: 17, family: 56, solo: 4, conflict: 9 } },
  { title: "The White Castle", year: 2023, categories: ["Euro", "Dice Placement"], mechanics: ["Dice Placement", "Resource Conversion", "Combo Planning"], minPlayers: 1, maxPlayers: 4, complexity: 3.0, playTime: 80, hook: "squeeze breathtaking efficiency out of a compact dice-placement euro", buzz: 80, rising: 81, tasteProfile: { strategy: 88, thematic: 39, party: 8, family: 21, solo: 67, conflict: 17 } },
  { title: "Beyond the Sun", year: 2020, categories: ["Tech Tree", "Strategy"], mechanics: ["Technology Tracks", "Worker Placement", "Area Expansion"], minPlayers: 2, maxPlayers: 4, complexity: 3.6, playTime: 110, hook: "unlock a communal tech tree that transforms every future decision", buzz: 75, rising: 42, tasteProfile: { strategy: 93, thematic: 45, party: 5, family: 16, solo: 52, conflict: 37 } },
  { title: "Decrypto", year: 2018, categories: ["Party", "Word Game"], mechanics: ["Code Cracking", "Teams", "Deduction"], minPlayers: 3, maxPlayers: 8, complexity: 2.0, playTime: 30, hook: "mix code-cracking tension with the joy of trying to sound obvious without being obvious", buzz: 71, rising: 31, tasteProfile: { strategy: 49, thematic: 24, party: 94, family: 74, solo: 2, conflict: 16 } },
  { title: "Tiny Towns", year: 2019, categories: ["Puzzle", "Family"], mechanics: ["Pattern Building", "Resource Drafting", "Spatial Planning"], minPlayers: 1, maxPlayers: 6, complexity: 2.0, playTime: 45, hook: "fit polyomino-like buildings into a tiny grid without painting yourself into a corner", buzz: 69, rising: 37, tasteProfile: { strategy: 66, thematic: 31, party: 27, family: 76, solo: 43, conflict: 9 } },
  { title: "Sea Salt & Paper", year: 2022, categories: ["Card Game", "Set Collection"], mechanics: ["Hand Management", "Push Your Luck", "Set Collection"], minPlayers: 2, maxPlayers: 4, complexity: 1.6, playTime: 30, hook: "fold a tiny card game into a push-your-luck delight with surprising tactical teeth", buzz: 70, rising: 65, tasteProfile: { strategy: 51, thematic: 38, party: 57, family: 79, solo: 11, conflict: 12 } },
  { title: "SETI: Search for Extraterrestrial Intelligence", year: 2024, categories: ["Sci-Fi", "Strategy"], mechanics: ["Action Selection", "Resource Management", "Research Tracks"], minPlayers: 1, maxPlayers: 4, complexity: 4.1, playTime: 140, hook: "scan the stars, upgrade probes, and chase scientific prestige with delicious euro tension", buzz: 90, rising: 94, tasteProfile: { strategy: 96, thematic: 68, party: 6, family: 11, solo: 74, conflict: 22 } },
  { title: "A Feast for Odin", year: 2016, categories: ["Euro", "Sandbox"], mechanics: ["Worker Placement", "Polyomino Filling", "Resource Conversion"], minPlayers: 1, maxPlayers: 4, complexity: 4.2, playTime: 150, hook: "draft a Viking livelihood across dozens of actions and a wildly rewarding puzzle board", buzz: 83, rising: 41, tasteProfile: { strategy: 95, thematic: 52, party: 4, family: 9, solo: 81, conflict: 18 } },
  { title: "Arcs", year: 2024, categories: ["Sci-Fi", "Conflict"], mechanics: ["Trick Taking", "Area Control", "Action Selection"], minPlayers: 2, maxPlayers: 4, complexity: 3.8, playTime: 110, hook: "turn a tiny action deck into explosive space politics and sudden reversals", buzz: 91, rising: 96, tasteProfile: { strategy: 86, thematic: 82, party: 14, family: 12, solo: 24, conflict: 94 } },
  { title: "Carnegie", year: 2022, categories: ["Economic", "Euro"], mechanics: ["Action Selection", "Network Building", "Resource Management"], minPlayers: 1, maxPlayers: 4, complexity: 3.7, playTime: 120, hook: "build a philanthropic business empire through sharp action timing and shared incentives", buzz: 74, rising: 54, tasteProfile: { strategy: 92, thematic: 36, party: 6, family: 14, solo: 63, conflict: 22 } },
  { title: "The Castles of Burgundy", year: 2011, categories: ["Euro", "Dice Strategy"], mechanics: ["Dice Drafting", "Tile Placement", "Set Collection"], minPlayers: 2, maxPlayers: 4, complexity: 3.0, playTime: 90, hook: "turn dice luck into long-term planning across one of the cleanest point-salad euros ever made", buzz: 82, rising: 34, tasteProfile: { strategy: 88, thematic: 27, party: 8, family: 26, solo: 41, conflict: 14 } },
  { title: "Ticket to Ride", year: 2004, categories: ["Family", "Route Building"], mechanics: ["Set Collection", "Route Building", "Hand Management"], minPlayers: 2, maxPlayers: 5, complexity: 1.9, playTime: 50, hook: "claim rail lines with an evergreen ruleset that still creates perfect little races", buzz: 79, rising: 18, tasteProfile: { strategy: 52, thematic: 47, party: 31, family: 95, solo: 6, conflict: 26 } },
  { title: "Patchwork", year: 2014, categories: ["Abstract", "Two-Player"], mechanics: ["Tile Placement", "Time Track", "Economic Choices"], minPlayers: 2, maxPlayers: 2, complexity: 1.8, playTime: 25, hook: "turn a tiny quilt puzzle into a deliciously mean duel for buttons and tempo", buzz: 77, rising: 22, tasteProfile: { strategy: 69, thematic: 23, party: 11, family: 78, solo: 4, conflict: 28 } },
  { title: "Jaipur", year: 2009, categories: ["Card Game", "Two-Player"], mechanics: ["Set Collection", "Hand Management", "Market Manipulation"], minPlayers: 2, maxPlayers: 2, complexity: 1.6, playTime: 30, hook: "trade goods in a tiny two-player classic where tempo swings matter every round", buzz: 72, rising: 24, tasteProfile: { strategy: 58, thematic: 39, party: 18, family: 72, solo: 3, conflict: 32 } },
  { title: "The Quest for El Dorado", year: 2017, categories: ["Adventure", "Family"], mechanics: ["Deck Building", "Racing", "Hand Management"], minPlayers: 2, maxPlayers: 4, complexity: 2.0, playTime: 50, hook: "race through a modular jungle in a deckbuilder that never forgets to stay breezy", buzz: 76, rising: 46, tasteProfile: { strategy: 63, thematic: 69, party: 37, family: 83, solo: 18, conflict: 24 } },
  { title: "Orléans", year: 2014, categories: ["Euro", "Bag Building"], mechanics: ["Bag Building", "Worker Placement", "Engine Building"], minPlayers: 2, maxPlayers: 4, complexity: 3.1, playTime: 95, hook: "build a perfect medieval workforce out of a bag that keeps evolving every round", buzz: 74, rising: 37, tasteProfile: { strategy: 86, thematic: 44, party: 7, family: 21, solo: 46, conflict: 15 } },
  { title: "Obsession", year: 2018, categories: ["Thematic", "Strategy"], mechanics: ["Worker Placement", "Card Management", "Set Collection"], minPlayers: 1, maxPlayers: 4, complexity: 3.2, playTime: 100, hook: "run an aristocratic estate where social climbing and servant timing feel wonderfully dramatic", buzz: 78, rising: 61, tasteProfile: { strategy: 72, thematic: 91, party: 12, family: 22, solo: 66, conflict: 19 } },
  { title: "Sleeping Gods", year: 2021, categories: ["Adventure", "Campaign"], mechanics: ["Open World", "Narrative Choices", "Hand Management"], minPlayers: 1, maxPlayers: 4, complexity: 3.1, playTime: 120, hook: "sail a branching storybook world packed with side quests, discoveries, and hard choices", buzz: 80, rising: 49, tasteProfile: { strategy: 61, thematic: 97, party: 9, family: 17, solo: 84, conflict: 26 } },
  { title: "Hansa Teutonica", year: 2009, categories: ["Economic", "Interaction"], mechanics: ["Route Building", "Network Building", "Action Improvement"], minPlayers: 2, maxPlayers: 5, complexity: 3.2, playTime: 75, hook: "weaponize route blocking and upgrade timing inside one of the sharpest interaction euros around", buzz: 71, rising: 44, tasteProfile: { strategy: 91, thematic: 24, party: 5, family: 16, solo: 14, conflict: 48 } },
  { title: "Res Arcana", year: 2019, categories: ["Card Game", "Engine Building"], mechanics: ["Hand Management", "Resource Conversion", "Race"], minPlayers: 2, maxPlayers: 4, complexity: 2.6, playTime: 40, hook: "forge a tiny mage engine where every card pulls absurd weight from turn one", buzz: 75, rising: 39, tasteProfile: { strategy: 82, thematic: 58, party: 14, family: 29, solo: 21, conflict: 23 } },
  { title: "Point Salad", year: 2019, categories: ["Card Game", "Family"], mechanics: ["Drafting", "Set Collection", "Open Information"], minPlayers: 2, maxPlayers: 6, complexity: 1.4, playTime: 20, hook: "draft vegetables and scoring cards in a filler that always feels one turn too short", buzz: 67, rising: 33, tasteProfile: { strategy: 48, thematic: 19, party: 43, family: 86, solo: 8, conflict: 7 } },
  { title: "Camel Up", year: 2014, categories: ["Party", "Racing"], mechanics: ["Betting", "Dice Rolling", "Shared Incentives"], minPlayers: 3, maxPlayers: 8, complexity: 1.5, playTime: 30, hook: "bet on camels stacking, collapsing, and sprinting into chaos while the whole table yells", buzz: 73, rising: 28, tasteProfile: { strategy: 33, thematic: 57, party: 93, family: 82, solo: 1, conflict: 18 } },
  { title: "Lords of Waterdeep", year: 2012, categories: ["Worker Placement", "Fantasy"], mechanics: ["Worker Placement", "Quest Collection", "Take-That Cards"], minPlayers: 2, maxPlayers: 5, complexity: 2.5, playTime: 75, hook: "use a welcoming worker-placement shell to race for quests and the occasional nasty intrigue card", buzz: 70, rising: 26, tasteProfile: { strategy: 65, thematic: 62, party: 16, family: 48, solo: 9, conflict: 27 } },
  { title: "Blood on the Clocktower", year: 2022, categories: ["Social Deduction", "Party"], mechanics: ["Hidden Roles", "Storytelling", "Deduction"], minPlayers: 5, maxPlayers: 20, complexity: 2.6, playTime: 90, hook: "turn social deduction into a theatrical mystery where even dead players still matter", buzz: 88, rising: 73, tasteProfile: { strategy: 51, thematic: 79, party: 98, family: 34, solo: 1, conflict: 62 } },
  { title: "Paleo", year: 2020, categories: ["Co-op", "Survival"], mechanics: ["Scenario Goals", "Hand Management", "Card Drafting"], minPlayers: 2, maxPlayers: 4, complexity: 2.6, playTime: 60, hook: "survive a stone-age gauntlet by reading limited information and committing to risky hunts together", buzz: 71, rising: 32, tasteProfile: { strategy: 61, thematic: 73, party: 16, family: 43, solo: 18, conflict: 8 } },
  { title: "Great Western Trail", year: 2016, categories: ["Euro", "Economic"], mechanics: ["Deck Building", "Movement", "Worker Placement"], minPlayers: 2, maxPlayers: 4, complexity: 3.7, playTime: 120, hook: "drive cattle across a route that keeps expanding your tactical options every delivery", buzz: 84, rising: 43, tasteProfile: { strategy: 94, thematic: 48, party: 5, family: 14, solo: 44, conflict: 31 } },
  { title: "Castle Combo", year: 2024, categories: ["Card Game", "Puzzle"], mechanics: ["Card Drafting", "Pattern Building", "Combo Chaining"], minPlayers: 2, maxPlayers: 5, complexity: 2.0, playTime: 25, hook: "chain tiny tableau effects into a compact score attack that feels bigger than the box", buzz: 78, rising: 87, tasteProfile: { strategy: 64, thematic: 41, party: 36, family: 74, solo: 15, conflict: 9 } },
];

export const awardSeeds = [
  ["Cascadia", "Spiel des Jahres", 2022, "Winner"],
  ["Dorfromantik", "Spiel des Jahres", 2023, "Winner"],
  ["Sky Team", "Spiel des Jahres", 2024, "Winner"],
  ["Scout", "Spiel des Jahres", 2022, "Recommended"],
  ["The Crew", "Kennerspiel des Jahres", 2020, "Winner"],
  ["Ark Nova", "Golden Geek Heavy Game of the Year", 2021, "Winner"],
  ["Heat: Pedal to the Metal", "Golden Geek Board Game of the Year", 2022, "Nominee"],
  ["Brass: Birmingham", "Golden Geek Heavy Game of the Year", 2018, "Nominee"],
  ["Wingspan", "Kennerspiel des Jahres", 2019, "Winner"],
  ["Spirit Island", "Golden Geek Cooperative Game of the Year", 2017, "Winner"],
  ["Root", "Golden Geek Thematic Game of the Year", 2018, "Winner"],
  ["The White Castle", "Golden Geek Medium Game of the Year", 2023, "Nominee"],
  ["Ready Set Bet", "Golden Geek Party Game of the Year", 2022, "Nominee"],
  ["Sea Salt & Paper", "As d'Or Initié", 2023, "Nominee"],
  ["Harmonies", "As d'Or Jeu de l'Année", 2024, "Nominee"],
  ["Crokinole", "Golden Geek Light Game of the Year", 2024, "Nominee"],
  ["SETI: Search for Extraterrestrial Intelligence", "GamePulse Rising Star", 2024, "Winner"],
  ["Dune: Imperium", "Golden Geek Medium Game of the Year", 2020, "Winner"],
  ["Lost Ruins of Arnak", "Golden Geek Medium Game of the Year", 2021, "Nominee"],
  ["The Quacks of Quedlinburg", "Kennerspiel des Jahres", 2018, "Winner"],
  ["Pandemic Legacy: Season 1", "Golden Geek Board Game of the Year", 2015, "Winner"],
  ["Codenames", "Spiel des Jahres", 2015, "Winner"],
  ["Sky Team", "As d'Or Jeu de l'Année", 2024, "Winner"],
  ["Splendor Duel", "Golden Geek Two-Player Game of the Year", 2022, "Nominee"],
] as const;

export const releaseCalendarSeeds = [
  ["SETI: Deep Signals", "2026-06-20", "Expansion", 88, "Adds campaign-style alien contact scenarios, solo events, and harder research races."],
  ["Sky Team: Turbulence", "2026-07-04", "Expansion", 84, "New airports, harsher weather modules, and tighter communication restrictions for veteran crews."],
  ["Project Aurora", "2026-07-18", "New Release", 79, "A debut sci-fi euro already spiking in critic anticipation after convention demos."],
  ["Meadowlights", "2026-08-02", "New Release", 76, "A family nature puzzler from a breakout design duo with easy-to-teach pattern play."],
  ["Root: Borderlands", "2026-08-14", "Expansion", 86, "Two new factions, refreshed hirelings, and tighter two-player maps."],
  ["Mariners of Europa", "2026-09-09", "New Release", 82, "A medium-heavy trade game with strong preview buzz and a dynamic market board."],
  ["Harmonies: Moon Garden", "2026-09-26", "Expansion", 74, "Adds nocturnal wildlife scoring cards and a more tactical advanced mode."],
  ["Crokinole Masters Circuit", "2026-10-03", "Event", 68, "Regional finals are driving renewed interest in premium tournament boards."],
  ["Nemesis: Void Seeders", "2026-10-17", "Expansion", 85, "Introduces a new threat deck and branching objective chains for co-op crews."],
  ["Cascadia: Alpine Trails", "2026-11-07", "Expansion", 73, "Seasonal scoring modules and linked scenarios for cozy campaign play."],
  ["Dune: Imperium - Bloodlines", "2026-11-21", "Expansion", 90, "A sharper intrigue deck and new leaders are already generating massive chatter."],
  ["Golden Geek Awards Livestream", "2026-12-05", "Event", 71, "Watchlist-worthy reminder for award season debates and publisher reveal teases."],
] as const;
